// <auto-generated />
using System;
using ClothingStore.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStore.DAL.Migrations
{
    [DbContext(typeof(ClothingStoreDbContext))]
    [Migration("20230313155711_Base+Dimensions")]
    partial class BaseDimensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStore.DAL.Entities.Brands", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Colors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.CriteriaOfDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxSize")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int?>("MinSize")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("namesCriteriaOfDimensionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("namesCriteriaOfDimensionsId");

                    b.ToTable("CriteriaOfDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.Dimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CriteriaOfDimensionsId")
                        .HasColumnType("int");

                    b.Property<int?>("UnionNamesAndDimensionsId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("sizesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaOfDimensionsId");

                    b.HasIndex("UnionNamesAndDimensionsId");

                    b.HasIndex("sizesId");

                    b.ToTable("Dimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.NamesCriteriaOfDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NamesCriteriaOfDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.NamesDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("NamesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.Sizes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("namesDimensionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("namesDimensionsId");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.TypesDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("typeHumanId")
                        .HasColumnType("int");

                    b.Property<int?>("typeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("typeHumanId");

                    b.HasIndex("typeId");

                    b.ToTable("TypesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesAndDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NamesDimensionsId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("typeDimensionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NamesDimensionsId");

                    b.HasIndex("typeDimensionsId");

                    b.ToTable("UnionNamesAndDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesCriteriaOfDimensions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NamesCriteriaOfDimensionsId")
                        .HasColumnType("int");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("typesDimensionsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NamesCriteriaOfDimensionsId");

                    b.HasIndex("typesDimensionsId");

                    b.ToTable("UnionNamesCriteriaOfDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.TypesHuman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TypesHumans");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.CriteriaOfDimensions", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.UnionNamesCriteriaOfDimensions", "namesCriteriaOfDimensions")
                        .WithMany("criteriaOfDimensions")
                        .HasForeignKey("namesCriteriaOfDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("namesCriteriaOfDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.Dimensions", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.CriteriaOfDimensions", "CriteriaOfDimensions")
                        .WithMany("dimensions")
                        .HasForeignKey("CriteriaOfDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.UnionNamesAndDimensions", null)
                        .WithMany("dimensions")
                        .HasForeignKey("UnionNamesAndDimensionsId");

                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.Sizes", "sizes")
                        .WithMany("Dimensions")
                        .HasForeignKey("sizesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CriteriaOfDimensions");

                    b.Navigation("sizes");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.Sizes", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.UnionNamesAndDimensions", "namesDimensions")
                        .WithMany("sizes")
                        .HasForeignKey("namesDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("namesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.TypesDimensions", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.TypesHuman", "typeHuman")
                        .WithMany("TypesDimensions")
                        .HasForeignKey("typeHumanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClothingStore.DAL.Entities.Types", "type")
                        .WithMany("TypesDimensions")
                        .HasForeignKey("typeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("type");

                    b.Navigation("typeHuman");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesAndDimensions", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.NamesDimensions", "NamesDimensions")
                        .WithMany("union")
                        .HasForeignKey("NamesDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.TypesDimensions", "typeDimensions")
                        .WithMany("namesDimensions")
                        .HasForeignKey("typeDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NamesDimensions");

                    b.Navigation("typeDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesCriteriaOfDimensions", b =>
                {
                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.NamesCriteriaOfDimensions", "NamesCriteriaOfDimensions")
                        .WithMany("union")
                        .HasForeignKey("NamesCriteriaOfDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClothingStore.DAL.Entities.Dimensions.TypesDimensions", "typesDimensions")
                        .WithMany("namesCriteria")
                        .HasForeignKey("typesDimensionsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NamesCriteriaOfDimensions");

                    b.Navigation("typesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.CriteriaOfDimensions", b =>
                {
                    b.Navigation("dimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.NamesCriteriaOfDimensions", b =>
                {
                    b.Navigation("union");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.NamesDimensions", b =>
                {
                    b.Navigation("union");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.Sizes", b =>
                {
                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.TypesDimensions", b =>
                {
                    b.Navigation("namesCriteria");

                    b.Navigation("namesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesAndDimensions", b =>
                {
                    b.Navigation("dimensions");

                    b.Navigation("sizes");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Dimensions.UnionNamesCriteriaOfDimensions", b =>
                {
                    b.Navigation("criteriaOfDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.Types", b =>
                {
                    b.Navigation("TypesDimensions");
                });

            modelBuilder.Entity("ClothingStore.DAL.Entities.TypesHuman", b =>
                {
                    b.Navigation("TypesDimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
